# Generated by Django 2.1.3 on 2018-11-15 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cod_empresa_erp', models.IntegerField(null=True, verbose_name='Codigo Empresa ERP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50, verbose_name='Cliente')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('E', 'Encerrado'), ('D', 'Descartado')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
        migrations.CreateModel(
            name='LeadAcoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesse', models.CharField(blank=True, choices=[('N', 'Novos'), ('U', 'Seminovos'), ('C', 'Consorcio'), ('T', 'Tele-Pecas'), ('S', 'Seguros'), ('A', 'Acessorios')], max_length=1, null=True, verbose_name='Interesse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Lead Ação',
                'verbose_name_plural': 'Leads Ações',
            },
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cod_regiao_erp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
            },
        ),
        migrations.CreateModel(
            name='Termometro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Termômetro',
                'verbose_name_plural': 'Termômetros',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='termometro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='opportune.Termometro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regiao_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opportune.Regiao'),
        ),
    ]
