# Generated by Django 2.1.3 on 2018-11-15 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportune', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadacoes',
            name='lead',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Lead', to='opportune.Lead'),
        ),
    ]
